// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"GALV_LayerGraphicsMZ","status":true,"description":"(v.1.3) Create graphic layers for parallax mapping, fog, etc. View documentation for plugin commands.","parameters":{"fixPosition":"true"}},
{"name":"GALV_DiagonalMovement","status":true,"description":"(v.1.5) Just a basic diagonal movement plugin. Written for compatibility with other Galv plugins.","parameters":{"Diagonal Mouse":"true","Diagonal Charset":"true","Diagonal Speed":"90","Block Diagonal":"false"}},
{"name":"GabeMZ_StepSound","status":true,"description":"[v1.1.1] Allows characters to emit step sounds when walking.","parameters":{"stepSoundSettings":"[\"{\\\"baseName\\\":\\\"Step\\\",\\\"variance\\\":\\\"4\\\",\\\"volume\\\":\\\"70\\\",\\\"volumeVariance\\\":\\\"15\\\",\\\"pitch\\\":\\\"100\\\",\\\"pitchVariance\\\":\\\"0\\\",\\\"pan\\\":\\\"0\\\",\\\"panVariance\\\":\\\"0\\\"}\"]","playerStepSound":"true","followersStepSound":"true","walkingFrequency":"100","dashingFrequency":"90"}}
];
